;/*FB_PKG_DELIM*/

__d("FDSAppFacebookReelsFilled20Icon",["cr:14316"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14316")}),98);
__d("FDSAppFacebookReelsFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("155429"),20);b=a;g["default"]=b}),98);
__d("FDSFundraiserFilled20Icon",["cr:15027"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15027")}),98);
__d("FDSFundraiserFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("510954"),20);b=a;g["default"]=b}),98);
__d("FDSLifeEventFilled20Icon",["cr:15190"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15190")}),98);
__d("FDSLifeEventFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("481240"),20);b=a;g["default"]=b}),98);
__d("FDSStoriesFilled20Icon",["cr:15730"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15730")}),98);
__d("FDSStoriesFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("1160717"),20);b=a;g["default"]=b}),98);
__d("FundraiserGKUtils.entrypointutils",["gkx"],(function(a,b,c,d,e,f,g){"use strict";function h(){return c("gkx")("23096")}function a(){return h()}function b(){return c("gkx")("23094")&&h()}function d(){return c("gkx")("20935")}g.canCreateP4CFundraiser=h;g.canCreateFundraiser=a;g.canCreateChallenge=b;g.canSeeCometVoiceSwitcher=d}),98);
__d("XCometFundraiserWithPresenceCreateDialogControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/fundraiser/with_presence/create_dialog/",Object.freeze({is_comet_on_mobile:!1,source_data:{},default_open_dbop:!1}),void 0);b=a;g["default"]=b}),98);
__d("XFundraiserCreateForPageControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/fund/{?page_token}/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("FundraiserCreateUrlUtils",["FundraiserGKUtils.entrypointutils","XCometFundraiserWithPresenceCreateDialogControllerRouteBuilder","XFundraiserCreateForPageControllerRouteBuilder"],(function(a,b,c,d,e,f,g){"use strict";function h(a,b,c,e,f,g,h){if(!d("FundraiserGKUtils.entrypointutils").canCreateP4CFundraiser())return null;var j={default_beneficiary_type:"charity"};g===!0&&(j.default_default_donation_type="recurring_donation");b!=null&&(j.default_beneficiary_id=b);c!=null&&(j.page_id=c);e!=null&&(j.challenge_id=e);f!=null&&(j.prefill_type=f);h!=null&&(j.is_comet_on_mobile=h);return i(j,a)}function a(a,b,c,e,f,g,j,k){if(!d("FundraiserGKUtils.entrypointutils").canCreateFundraiser())return null;switch(a){case 6:return h(b,c,e,f,g,j,k);default:return i(null,b)}}function i(a,b){a=(a=a)!=null?a:{};b!=null&&(a.source=b);return c("XCometFundraiserWithPresenceCreateDialogControllerRouteBuilder").buildURL(a).toString()}function b(a){return c("XFundraiserCreateForPageControllerRouteBuilder").buildURL({page_token:a}).toString()}g.getCreatePersonToCharityFundraiserUrl=h;g.getCreateFundraiserUrl=a;g.getCreateUrl=i;g.getPageCreationShortUrl=b}),98);
__d("XCometPageCreationControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/pages/creation/",Object.freeze({should_lwi_redirect:!1}),void 0);b=a;g["default"]=b}),98);
__d("useProfileCometLifeEventsComposerDialog",["react-compiler-runtime","useProfileCometInlineComposer"],(function(a,b,c,d,e,f,g){"use strict";function a(a){var b=d("react-compiler-runtime").c(11),e=a.isFromMegaMenu;a=a.profileID;var f;b[0]!==a?(f={profileID:a,shouldOpenVideoSpecificComposer:!1},b[0]=a,b[1]=f):f=b[1];a=c("useProfileCometInlineComposer")(f);var g=a[0];f=a[1];var h=a[2],i=a[3];a=a[4];var j;b[2]!==g||b[3]!==e?(j=function(){g({isFromMegaMenu:e,pushedPageOnLoad:"mle"})},b[2]=g,b[3]=e,b[4]=j):j=b[4];j=j;var k;b[5]!==h||b[6]!==i||b[7]!==j||b[8]!==a||b[9]!==f?(k=[j,f,h,i,a],b[5]=h,b[6]=i,b[7]=j,b[8]=a,b[9]=f,b[10]=k):k=b[10];return k}g["default"]=a}),98);
__d("useShowCometUnifiedVideoCreationDialog",["CometUnifiedVideoCreationDialog.entrypoint","react-compiler-runtime","useCometEntryPointDialog"],(function(a,b,c,d,e,f,g){"use strict";function a(a){var b=d("react-compiler-runtime").c(8);a=c("useCometEntryPointDialog")(c("CometUnifiedVideoCreationDialog.entrypoint"),a);var e=a[0],f=a[1],g=a[2],h=a[3];a=a[4];var i;b[0]!==e?(i=function(a){return e(a)},b[0]=e,b[1]=i):i=b[1];i=i;var j;b[2]!==a||b[3]!==f||b[4]!==g||b[5]!==i||b[6]!==h?(j=[i,f,g,h,a],b[2]=a,b[3]=f,b[4]=g,b[5]=i,b[6]=h,b[7]=j):j=b[7];return j}g["default"]=a}),98);